version: '3.8'

services:
  iotcontroller:
    build:
      context: .
      dockerfile: Dockerfile
    image: iotcontroller:latest
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      iot:
        aliases:
          - iotcontroller

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      iot:
        aliases:
            - prometheus
    deploy:
      replicas: 1

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      iot:
        aliases:
            - grafana
    deploy:
      replicas: 1

volumes:
  rabbitmq_data:

networks:
  iot:
    driver: overlay